
import 'jquery'
import 'popper.js'
import './js/common'
import './css/main.css'
import './scss/style.scss'
import '../components/room__search/room__search.scss'
import '../components/calendar/calendar.scss'
import '../components/enter/enter.scss'
import '../components/registration/registration.scss'
import '../components/room__number/room__number.scss'
import '../components/roomNumber__840/roomNumber__840.scss'
import '../components/roomNumber__888/roomNumber__888.scss'
import '../Form_Elements/text_field/text_field.scss'
import '../Form_Elements/dropdown/dropdown_vis.scss'
import '../Form_Elements/masked_text_field/masked_text_field.scss'

